export const passageA = {
    "paragraph1": 'The Meissner effect (or Meissner–Ochsenfeld effect) is the expulsion of a magnetic field from a superconductor during its transition to the superconducting state. The German physicists Walther Meissner and Robert Ochsenfeld discovered this phenomenon in 1933 by measuring the magnetic field distribution outside superconducting tin and lead samples. The samples, in the presence of an applied magnetic field, were cooled below their superconducting transition temperature, whereupon the samples cancelled nearly all interior magnetic fields. They detected this effect only indirectly because the magnetic flux is conserved by a superconductor: when the interior field decreases, the exterior field increases. The experiment demonstrated for the first time that superconductors were more than just perfect conductors and provided a uniquely defining property of the superconductor state. The ability for the expulsion effect is determined by the nature of equilibrium formed by the neutralization within the unit cell of a superconductor.',
    "paragraph2": 'A superconductor with little or no magnetic field within it is said to be in the Meissner state. The Meissner state breaks down when the applied magnetic field is too large. Superconductors can be divided into two classes according to how this breakdown occurs. In type-I superconductors, superconductivity is abruptly destroyed when the strength of the applied field rises above a critical value Hc. Depending on the geometry of the sample, one may obtain an intermediate state consisting of a baroque pattern of regions of normal material carrying a magnetic field mixed with regions of superconducting material containing no field. In type-II superconductors, raising the applied field past a critical value Hc1 leads to a mixed state (also known as the vortex state) in which an increasing amount of magnetic flux penetrates the material, but there remains no resistance to the electric current as long as the current is not too large. At a second critical field strength Hc2, superconductivity is destroyed. The mixed state is caused by vortices in the electronic superfluid, sometimes called fluxons because the flux carried by these vortices is quantized. Most pure elemental superconductors, except niobium and carbon nanotubes, are type I, while almost all impure and compound superconductors are type II.',
    "paragraph3": 'The Meissner effect was given a phenomenological explanation by the brothers Fritz and Heinz London, who showed that the electromagnetic free energy in a superconductor is minimized provided',
    "paragraph4": 'In a weak applied field, a superconductor "expels" nearly all magnetic flux. It does this by setting up electric currents near its surface. The magnetic field of these surface currents cancels the applied magnetic field within the bulk of the superconductor. As the field expulsion, or cancellation, does not change with time, the currents producing this effect (called persistent currents) do not decay with time.',
    "paragraph5": 'Near the surface, within the London penetration depth, the magnetic field is not completely cancelled. Each superconducting material has its own characteristic penetration depth.',
    "paragraph6": 'Any perfect conductor will prevent any change to magnetic flux passing through its surface due to ordinary electromagnetic induction at zero resistance. The Meissner effect is distinct from this: when an ordinary conductor is cooled so that it makes the transition to a superconducting state in the presence of a constant applied magnetic field, the magnetic flux is expelled during the transition. This effect cannot be explained by infinite conductivity. The placement and subsequent levitation of a magnet above an already superconducting material does not demonstrate the Meissner effect, while an initially stationary magnet later being repelled by a superconductor as it is cooled through its critical temperature does.',
    "paragraph7": 'Superconductors in the Meissner state exhibit perfect diamagnetism, or superdiamagnetism, meaning that the total magnetic field is very close to zero deep inside them (many penetration depths from the surface). This means that their magnetic susceptibility, Xv = −1. Diamagnetics are defined by the generation of a spontaneous magnetization of a material which directly opposes the direction of an applied field. However, the fundamental origins of diamagnetism in superconductors and normal materials are very different. In normal materials diamagnetism arises as a direct result of the orbital spin of electrons about the nuclei of an atom induced electromagnetically by the application of an applied field. In superconductors the illusion of perfect diamagnetism arises from persistent screening currents which flow to oppose the applied field (the Meissner effect); not solely the orbital spin.',
    "paragraph8": 'The discovery of the Meissner effect led to the phenomenological theory of superconductivity by Fritz and Heinz London in 1935. This theory explained resistanceless transport and the Meissner effect, and allowed the first theoretical predictions for superconductivity to be made. However, this theory only explained experimental observations—it did not allow the microscopic origins of the superconducting properties to be identified. This was done successfully by the BCS theory in 1957, from which the penetration depth and the Meissner effect result. However, some physicists argue that BCS theory does not explain the Meissner effect.',
};
export const passageB = {
  "paragraph1": "Hima Das (born 9 January 2000) is an Indian sprinter from the state of Assam, nicknamed the Dhing Express by the media. She became the first Indian to win a Gold in a track event at the IAAF World U20 Championships, when she ran the Women's 400 metres at Tampere version of the Games, 2018 in 51.46 seconds. She holds the current Indian national record in 400 metres women's race with a timing of 50.79 s that she clocked in the Jakarta Palembang 2018 Asian Games winning the silver medal.",
    "paragraph2": "Hima Das was born at Kandhulimari village, near Dhing Town of Nagaon district in the state of Assam to Ronjit and Jonali Das, who are rice farmers by profession. She is the youngest of five children. She attended the Dhing Public high School and was initially interested in playing football during her childhood. She played football with the boys at her school and had always wanted to pursue a career in football. However, she did not see any prospects for herself in women's football in India. She was even unsure if India had a National Women's Football team or not. Later, one of her school teachers suggested her to try athletics and subsequently she decided to switch over and began participating in short and middle distance races.",
    "paragraph3": "Hima was initially coached by Nipon Das, an athletics coach from the Directorate of Sports and Youth Welfare and during this time participated in an inter-district competition. On seeing her potential, Coach Das then asked her to shift to Guwahati for better training. Hima Das's parents reluctantly agreed to the proposal to move farther away. She then moved to a place near Saarusajai Sports Complex in Guwahati and enrolled to the state academy.",
    "paragraph4": "Das competed at the 2018 Commonwealth Games in the 400 metres and the 4x400 metres relay. In the 400 metres, Das qualified for the final where she finished sixth in a time of 51.32 seconds, 1.17 seconds behind gold medalist Amantle Montsho from Botswana. In the 4x400 metres relay she was part of the Indian team that competed in the final. They finished seventh, with a time of 3 minutes and 33.61 seconds.",
    "paragrpah5": "Das became the first Indian sprinter to win a Gold at a world meet when she ran to her victory at the World U-20 Championships 2018 at Tampere, Finland, in Women's 400m clocking a timing of 51.46 seconds. Having run a slower first half, Das accelerated on the last 100 meter stretch overtaking three competitors en route to the gold medal. Das is now part of a group of Indian athletes who have won medals at the World U20 Championships, which includes Seema Punia (Bronze, Discus throw), Navjeet Kaur Dhillon (Bronze, Discus throw) and Neeraj Chopra (Gold, Javelin throw).",
    "paragraph6": "At the Jakarta Palembang 2018 Asian Games, Das qualified for the final of the Women's 400 metres by clocking 51.00s in Heat 1, setting a new Indian National Record and finishing second in the qualification round. On 26 August 2018, she set the Indian National record again when she bettered her time to 50.79 sec in the final of the 400m to finish second to win the Silver medal. In Women's 4 × 400 metres relay on 30th August, 2018, she, along with Poovamma Raju Machettira, Saritaben Laxmanbhai Gayakwad and Vismaya Velluva Koroth won the gold medal for India clocking 3m 28.72s to complete the race. Earlier on the same date, due to her false start in semi final, Hima could not qualify for the final event of the Women's 200 meter race scheduled for the next day along with one Hajar Alkhaldi of Bahrain, who also made the same mistake in the next go. In the third go, the race started only with six athletes competing on the tracks."
};
export const passageC = {
    "paragraph1": "The Third Battle of Panipat took place on 14 January 1761 at Panipat, about 60 miles (97 km) north of Delhi, between a northern expeditionary force of the Maratha Empire and invading forces of the King of Afghanistan, Ahmad Shah Abdali, supported by two Indian allies—the Rohilla Afghans of the Doab, and Shuja-ud-Daula, the Nawab of Awadh. Militarily, the battle pitted the French origin artillery and cavalry of the Marathas against the heavy cavalry and mounted artillery (zamburak and jizail) of the Afghans and Rohillas led by Ahmad Shah Abdali and Najib-ud-Daulah, both ethnic Afghans (the former is also known as Ahmad Shah Durrani). The battle is considered one of the largest and most eventful fought in the 18th century, and has perhaps the largest number of fatalities in a single day reported in a classic formation battle between two armies.",
    "paragraph2": "The decline of the Mughal Empire following the 27-year Mughal-Maratha war (1680–1707) led to rapid territorial gains for the Maratha Empire. Under Peshwa Baji Rao, Gujarat, Malwa and Rajputana came under Maratha control. Finally, in 1737, Baji Rao defeated the Mughals on the outskirts of Delhi and brought much of the former Mughal territories south of Delhi under Maratha control. Baji Rao's son Balaji Baji Rao (popularly known as Nana Saheb) further increased the territory under Maratha control by invading Punjab in 1758. This brought the Marathas into direct confrontation with the Durrani empire of Ahmad Shah Abdali. In 1759 he raised an army from the Pashtun and Baloch tribes and made several gains against the smaller Maratha garrisons in Punjab. He then joined with his Indian allies—the Rohilla Afghans of the Gangetic Doab—forming a broad coalition against the Marathas. The Marathas, under the command of Sadashivrao Bhau, responded by gathering an army of between 45,000–60,000, which was accompanied by roughly 200,000 non-combatants, a number of whom were pilgrims desirous of making pilgrimages to Hindu holy sites in northern India. The Marathas started their northward journey from Patdur on 14 March 1760. Both sides tried to get the Nawab of Awadh, Shuja-ud-Daulah, into their camp. By late July Shuja-ud-Daulah made the decision to join the Afghan-Rohilla coalition, preferring to join what was perceived as" +  'the "army of Islam". This was strategically a major loss for the Marathas, since Shuja provided much-needed finances for the long Afghan stay in North India. It is doubtful whether the Afghan-Rohilla coalition would have the means to continue their conflict with the Marathas without ' +  "Shuja's support.",
    "paragraph3": "The slow-moving Maratha camp finally reached Delhi on 1 August 1760 and took the city the next day. There followed a series of skirmishes along the banks of the River Yamuna and a battle at Kunjpura, which the Marathas won against an Afghan garrison of about 15,000 (at this time Abdali and the other Afghan forces were on the eastern side of the Yamuna river). However, Abdali daringly crossed the Yamuna on 25 October at Baghpat, cutting off the Maratha camp from its base in Delhi. This eventually turned into a two-month-long siege led by Abdali against the Marathas in the town of Panipat. During the siege both sides tried to cut off the other's supplies. At this the Afghans were considerably more effective, so that by the end of November 1760 they had cut off almost all food supplies into the besieged Maratha camp (which consisted of about 250,0000-300,000, most of whom were non-combatants). According to all the chronicles of the time, food in the Maratha camp ran out by late December or early January and cattle died by the thousands. Reports of soldiers dying of starvation began to be heard in early January. On 13 January the Maratha chiefs begged their commander, Sadashiv Rao Bhau, to be allowed to die in battle rather than perish by starvation. The next day the Marathas left their camp before dawn and marched south towards the Afghan camp in a desperate attempt to break the siege. The two armies came face-to-face around 8:00 a.m., and the battle raged until evening.",
    "paragraph4": "The specific site of the battle itself is disputed by historians, but most consider it to have occurred somewhere near modern-day Kaalaa Aamb and Sanauli Road. The battle lasted for several days and involved over 125,000 troops. Protracted skirmishes occurred, with losses and gains on both sides. The forces led by Ahmad Shah Durrani came out victorious after destroying several Maratha flanks. The extent of the losses on both sides is heavily disputed by historians, but it is believed that between 60,000–70,000 were killed in fighting, while the numbers of injured and prisoners taken vary considerably. According to the single best eyewitness chronicle--the bakhar by Shuja-ud-Daulah's Diwan Kashi Raj--about 40,000 Maratha prisoners were slaughtered in cold blood the day after the battle. Grant Duff includes an interview of a survivor of these massacres in his History of the Marathas and generally corroborates this number. Shejwalkar, whose monograph Panipat 1761 is often regarded as the single best secondary source on the battle, " + 'says that "not less than 100,000 Marathas (soldiers and non-combatants) perished during and after the battle."',
    "paragraph5": "The result of the battle was the halting of further Maratha advances in the north, and a destabilization of their territories, for roughly ten years. This period is marked by the rule of Peshwa Madhavrao, who is credited with the revival of Maratha domination following the defeat at Panipat, ten years later in 1771.",
}
export const errorHandle = {
    'serviceDown': 'Service temporarily unavailable',
    'serviceDownSubtext': 'We are facing some technical issues. We will have it resolved shortly, please try again after some time.',
    'img': 'https://dg-static1.paytm.com/weex/images/gold/error.png',
    'contentNotSupported': 'Sorry this content is not supported',
    'contentNotSupportedSubHead': 'We will start supporting it soon.'
};